### PR TITLE
Dummy PR

### PR DESCRIPTION
**Pull request by dschonholtz**
* Useless comment

* Useless comment

### PR Quality Checklist
- [ ] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [ ] I have considered potential risks and mitigations for my changes.
- [ ] I have documented my changes clearly and comprehensively.
- [ ] I have not snuck in any "extra" small tweaks changes. 
- [ ] I have run `black .` and `isort .` against my code to ensure it passes our linter.

### CODE REVIEW

**Review by dschonholtz — COMMENTED** [review]
Iniital command work

**Review by dwrtz — CHANGES_REQUESTED** [review]
Testing Github API.

**Review by dwrtz — APPROVED** [review]
Looks good from Github API

**Review by swyxio — APPROVED** [review]
nice start!

**Review by dwrtz — APPROVED** [review]
Looks good from Github API

**Review by dwrtz — CHANGES_REQUESTED** [review]
Testing Github API.

**Review by dwrtz — CHANGES_REQUESTED** [review]
Testing Github API.

**Pull request merged**
